import { useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowRight, BookOpen } from 'lucide-react'

const DISPLAY = "'Playfair Display', Georgia, serif"
const UI      = "'Inter', system-ui, sans-serif"
const EASE    = [0.32, 0.72, 0, 1]

const C = {
  bg:      '#1a1410',
  surf:    '#231c16',
  raise:   '#2d2419',
  b1:      '#2a2018',
  b2:      '#3d3028',
  gold:    '#c9a96e',
  goldDim: 'rgba(201,169,110,0.08)',
  goldBdr: 'rgba(201,169,110,0.20)',
  t1:      '#f0e8d8',
  t2:      '#a89070',
  t3:      '#6b5540',
}

const INSIGHTS = [
  {
    category:   'Market Intelligence',
    headline:   "Understanding Risk-Adjusted Returns: What Your Portfolio's Sharpe Ratio Reveals",
    excerpt:    "Most investors track returns. Sophisticated investors track risk-adjusted returns. The Sharpe ratio measures how much return a portfolio generates for every unit of risk taken. A portfolio returning 15% with a Sharpe of 0.8 is actually worse than one returning 12% with a Sharpe of 1.6. The math tells a different story than the headline number.",
    concept:    'Sharpe Ratio',
    definition: "The return earned per unit of risk, calculated as (portfolio return − risk-free rate) ÷ standard deviation. A Sharpe above 1.0 is considered good. Above 2.0 is exceptional.",
    quote:      "The stock market is a device for transferring money from the impatient to the patient.",
    quoteAttr:  'Warren Buffett',
    href:       '/insights/sharpe-ratio',
    readTime:   '5 min read',
    books:      ['A Random Walk Down Wall Street', 'The Intelligent Investor', 'Common Stocks and Uncommon Profits'],
  },
  {
    category:   'Tax Strategy',
    headline:   "Tax Alpha: The Return Most Investors Leave on the Table Every Year",
    excerpt:    "Tax drag is one of the largest — and most preventable — sources of investment underperformance. The average investor loses 1.0 to 2.5% annually to avoidable taxes through poor asset location and failure to harvest losses. Tax alpha is the additional return generated by managing investments tax-efficiently. Over 30 years, this compounding difference is substantial.",
    concept:    'Tax Alpha',
    definition: "The additional investment return generated through tax-efficient portfolio management — including tax-loss harvesting, asset location optimization, and strategic gain realization timing.",
    quote:      "An investment in knowledge pays the best interest.",
    quoteAttr:  'Benjamin Franklin',
    href:       '/insights/tax-alpha',
    readTime:   '7 min read',
    books:      ['The Bogleheads Guide to Investing', 'Tax-Free Wealth', 'The Little Book of Common Sense Investing'],
  },
  {
    category:   'Retirement Planning',
    headline:   "The 4% Rule: What Bengen's Research Actually Says About Retirement Income",
    excerpt:    "In 1994, financial planner William Bengen published research showing that a retiree who withdrew 4% of their portfolio in year one — adjusted for inflation each year after — would not run out of money over any 30-year historical period. What the headlines miss: the rule assumes a specific equity allocation and exact 30-year horizon. Your circumstances change the math.",
    concept:    'Safe Withdrawal Rate',
    definition: "The percentage of a retirement portfolio that can be withdrawn annually — adjusted for inflation — without depleting the portfolio over a defined horizon. Bengen's research established 4% as the historical floor for 30-year retirements.",
    quote:      "Someone is sitting in the shade today because someone planted a tree a long time ago.",
    quoteAttr:  'Warren Buffett',
    href:       '/insights/four-percent-rule',
    readTime:   '6 min read',
    books:      ['Die With Zero', 'The Psychology of Money', 'Your Money or Your Life'],
  },
]

export default function FeaturedInsights() {
  const navigate = useNavigate()

  return (
    <div style={{ background: C.bg, minHeight: '100dvh', fontFamily: UI }}>

      {/* P button — back to home */}
      <button
        onClick={() => navigate('/')}
        title="Back to Home"
        style={{
          position: 'fixed', top: 20, right: 24, zIndex: 100,
          width: 38, height: 38, borderRadius: '50%',
          background: C.gold, border: 'none', cursor: 'pointer',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          boxShadow: '0 4px 16px rgba(201,169,110,0.3)',
          transition: 'transform 0.2s, box-shadow 0.2s',
        }}
        onMouseEnter={e => { e.currentTarget.style.transform = 'scale(1.08)'; e.currentTarget.style.boxShadow = '0 6px 24px rgba(201,169,110,0.45)' }}
        onMouseLeave={e => { e.currentTarget.style.transform = 'scale(1)';    e.currentTarget.style.boxShadow = '0 4px 16px rgba(201,169,110,0.3)' }}
      >
        <span style={{ fontFamily: DISPLAY, fontSize: 15, fontWeight: 800, color: '#1a1410', lineHeight: 1 }}>P</span>
      </button>

      {/* Header */}
      <div style={{ maxWidth: 1100, margin: '0 auto', padding: '72px 40px 0' }}>
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.55, ease: EASE }}
        >
          <div style={{ fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.2em', color: C.t3, fontWeight: 600, marginBottom: 12 }}>
            Featured Insights
          </div>
          <h1 style={{ fontFamily: DISPLAY, fontSize: 'clamp(28px,4vw,48px)', fontWeight: 700, color: C.t1, margin: '0 0 16px', letterSpacing: '-0.02em', lineHeight: 1.15 }}>
            Learn from the principles,<br />not the headlines.
          </h1>
          <p style={{ fontSize: 15, color: C.t2, lineHeight: 1.7, maxWidth: 560, margin: '0 0 56px' }}>
            Three concepts every serious investor should understand — explained clearly, without jargon.
          </p>
        </motion.div>

        {/* Insights */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 40, paddingBottom: 80 }}>
          {INSIGHTS.map((insight, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 24 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, ease: EASE, delay: i * 0.1 }}
              style={{
                background: C.surf,
                border: `1px solid ${C.b1}`,
                borderRadius: 20,
                overflow: 'hidden',
              }}
            >
              {/* Gold accent top line */}
              <div style={{ height: 3, background: `linear-gradient(90deg, ${C.gold}, transparent)` }} />

              <div style={{ padding: '36px 40px', display: 'grid', gridTemplateColumns: '1fr 340px', gap: 48, alignItems: 'start' }} className="insight-grid">

                {/* Left */}
                <div>
                  <div style={{
                    display: 'inline-flex', alignItems: 'center', gap: 6,
                    background: C.goldDim, border: `1px solid ${C.goldBdr}`,
                    borderRadius: 6, padding: '4px 10px', marginBottom: 20,
                  }}>
                    <span style={{ fontSize: 10, color: C.gold, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.12em' }}>
                      {insight.category}
                    </span>
                  </div>

                  <h2 style={{
                    fontFamily: DISPLAY, fontSize: 'clamp(20px,2vw,28px)',
                    fontWeight: 700, color: C.t1, lineHeight: 1.25,
                    margin: '0 0 18px', letterSpacing: '-0.02em',
                  }}>
                    {insight.headline}
                  </h2>

                  <p style={{ fontSize: 14, color: C.t2, lineHeight: 1.8, margin: '0 0 28px' }}>
                    {insight.excerpt}
                  </p>

                  {/* Quote */}
                  <div style={{ borderLeft: `2px solid ${C.gold}50`, paddingLeft: 20, marginBottom: 32 }}>
                    <p style={{ fontFamily: DISPLAY, fontSize: 15, fontStyle: 'italic', color: C.t2, margin: '0 0 8px', lineHeight: 1.55 }}>
                      &ldquo;{insight.quote}&rdquo;
                    </p>
                    <span style={{ fontSize: 11, color: C.t3 }}>— {insight.quoteAttr}</span>
                  </div>

                  <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
                    <button
                      onClick={() => navigate(insight.href)}
                      style={{
                        display: 'inline-flex', alignItems: 'center', gap: 8,
                        background: C.gold, border: 'none',
                        borderRadius: 9, padding: '10px 20px',
                        color: '#1a1410', fontSize: 13, fontWeight: 700,
                        cursor: 'pointer', transition: 'all 0.2s',
                      }}
                      onMouseEnter={e => e.currentTarget.style.filter = 'brightness(1.1)'}
                      onMouseLeave={e => e.currentTarget.style.filter = 'brightness(1)'}
                    >
                      Explore this section <ArrowRight size={13} />
                    </button>
                    <span style={{ fontSize: 11, color: C.t3 }}>{insight.readTime}</span>
                  </div>
                </div>

                {/* Right — concept card */}
                <div style={{
                  background: C.raise, border: `1px solid ${C.b2}`,
                  borderRadius: 14, padding: 24,
                }}>
                  <div style={{ fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.16em', color: C.t3, marginBottom: 10 }}>
                    Core Concept
                  </div>
                  <div style={{ fontFamily: DISPLAY, fontSize: 20, fontWeight: 700, color: C.gold, margin: '0 0 10px' }}>
                    {insight.concept}
                  </div>
                  <p style={{ fontSize: 13, color: C.t2, lineHeight: 1.7, margin: '0 0 22px' }}>
                    {insight.definition}
                  </p>

                  <div style={{ height: 1, background: C.b2, marginBottom: 18 }} />

                  <div style={{ fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.16em', color: C.t3, marginBottom: 12 }}>
                    Further Reading
                  </div>
                  {insight.books.map(book => (
                    <div key={book} style={{ display: 'flex', alignItems: 'flex-start', gap: 8, marginBottom: 8 }}>
                      <BookOpen size={11} color={C.t3} style={{ marginTop: 2, flexShrink: 0 }} />
                      <span style={{ fontSize: 12, color: C.t3, fontStyle: 'italic', lineHeight: 1.4 }}>{book}</span>
                    </div>
                  ))}
                </div>

              </div>
            </motion.div>
          ))}
        </div>
      </div>

      <style>{`
        @media (max-width: 860px) {
          .insight-grid { grid-template-columns: 1fr !important; }
        }
        @media (max-width: 600px) {
          .insight-grid { padding: 24px !important; }
        }
      `}</style>
    </div>
  )
}
