import { useEffect, useRef, useState } from 'react'
import { motion, useInView, AnimatePresence } from 'framer-motion'
import { useNavigate } from 'react-router-dom'
import { ArrowRight, ArrowUpRight, Search, X, TrendingUp, Clock, Shield, Home, Users, FileText, Wallet, Baby, BarChart2, Globe, LogOut, UserCircle, BookOpen } from 'lucide-react'
import { AreaChart, Area, ResponsiveContainer } from 'recharts'
import { useAuth } from '@/lib/AuthContext'

// ── Typography tokens — matching Arche exactly
const DISPLAY = "'Playfair Display', Georgia, serif"
const UI      = "'Inter', system-ui, sans-serif"
const MONO    = "'JetBrains Mono', 'Courier New', monospace"
const EASE    = [0.32, 0.72, 0, 1]

// ── Portfolio preview sparkline
const PORTFOLIO_SPARK = [
  { v: 221 }, { v: 228 }, { v: 224 }, { v: 237 }, { v: 243 },
  { v: 239 }, { v: 252 }, { v: 259 }, { v: 256 }, { v: 268 },
  { v: 272 }, { v: 266 }, { v: 280 }, { v: 284 }, { v: 279 }, { v: 284 },
]
const PORTFOLIO_METRICS = [
  { label: 'S&P Beta',   value: '1.04'   },
  { label: 'Sharpe',     value: '1.87'   },
  { label: 'YTD Return', value: '+28.4%' },
]

// ── S&P 500 sparkline for section preview card
const SP500_SPARK = [
  { v: 4880 }, { v: 4920 }, { v: 4895 }, { v: 4980 }, { v: 5040 },
  { v: 5010 }, { v: 5110 }, { v: 5090 }, { v: 5180 }, { v: 5210 },
  { v: 5280 }, { v: 5248 }, { v: 5340 }, { v: 5402 }, { v: 5388 },
  { v: 5471 }, { v: 5520 }, { v: 5498 }, { v: 5612 }, { v: 5847 },
]

// ── Featured insights
const INSIGHTS = [
  {
    category:  'Market Intelligence',
    headline:  "Understanding Risk-Adjusted Returns: What Your Portfolio's Sharpe Ratio Reveals",
    excerpt:   "Most investors track returns. Sophisticated investors track risk-adjusted returns. The Sharpe ratio measures how much return a portfolio generates for every unit of risk taken. A portfolio returning 15% with a Sharpe of 0.8 is actually worse than one returning 12% with a Sharpe of 1.6. The math tells a different story than the headline number.",
    concept:   'Sharpe Ratio',
    definition:"The return earned per unit of risk, calculated as (portfolio return − risk-free rate) ÷ standard deviation. A Sharpe above 1.0 is considered good. Above 2.0 is exceptional.",
    quote:     "The stock market is a device for transferring money from the impatient to the patient.",
    quoteAttr: 'Warren Buffett',
    href:      '/risk-analysis',
    readTime:  '5 min read',
    books:     ['A Random Walk Down Wall Street', 'The Intelligent Investor', 'Common Stocks and Uncommon Profits'],
  },
  {
    category:  'Tax Strategy',
    headline:  "Tax Alpha: The Return Most Investors Leave on the Table Every Year",
    excerpt:   "Tax drag is one of the largest — and most preventable — sources of investment underperformance. The average investor loses 1.0 to 2.5% annually to avoidable taxes through poor asset location and failure to harvest losses. Tax alpha is the additional return generated by managing investments tax-efficiently. Over 30 years, this compounding difference is substantial.",
    concept:   'Tax Alpha',
    definition:"The additional investment return generated through tax-efficient portfolio management — including tax-loss harvesting, asset location optimization, and strategic gain realization timing.",
    quote:     "An investment in knowledge pays the best interest.",
    quoteAttr: 'Benjamin Franklin',
    href:      '/tax-planning',
    readTime:  '7 min read',
    books:     ['The Bogleheads Guide to Investing', 'Tax-Free Wealth', 'The Little Book of Common Sense Investing'],
  },
  {
    category:  'Retirement Planning',
    headline:  "The 4% Rule: What Bengen's Research Actually Says About Retirement Income",
    excerpt:   "In 1994, financial planner William Bengen published research showing that a retiree who withdrew 4% of their portfolio in year one — adjusted for inflation each year after — would not run out of money over any 30-year historical period. What the headlines miss: the rule assumes a specific equity allocation and exact 30-year horizon. Your circumstances change the math.",
    concept:   'Safe Withdrawal Rate',
    definition:"The percentage of a retirement portfolio that can be withdrawn annually — adjusted for inflation — without depleting the portfolio over a defined horizon. Bengen's research established 4% as the historical floor for 30-year retirements.",
    quote:     "Someone is sitting in the shade today because someone planted a tree a long time ago.",
    quoteAttr: 'Warren Buffett',
    href:      '/retirement-planning',
    readTime:  '6 min read',
    books:     ['Die With Zero', 'The Psychology of Money', 'Your Money or Your Life'],
  },
]

// ── Nav links
const NAV_LINKS = [
  { label: 'Terminal', href: '/dashboard'     },
  { label: 'Wealth Counsel', href: '/wealth-counsel' },
  { label: 'FUN',      href: '/fun'           },
  { label: 'Markets',  href: '/MarketHistory' },
]

// ─────────────────────────────────────────────────────────────────────────────
// FLOATING PORTFOLIO PREVIEW CARD — hero right side
// ─────────────────────────────────────────────────────────────────────────────
// DAILY FINANCIAL FACTS — one per day, rotates by day-of-year
// ─────────────────────────────────────────────────────────────────────────────
const DAILY_FACTS = [
  {
    fact: "A $10,000 investment in the S&P 500 in 1994 would be worth over $220,000 today — without adding a single dollar.",
    concept: 'Compound Growth', stat: '22×', statLabel: '30-year S&P return', source: 'Bloomberg',
    category: 'Investing',
  },
  {
    fact: "The average American spends $18,000 per year on non-essential purchases. Invested at 7% over 30 years, that's $1.8 million in foregone wealth.",
    concept: 'Opportunity Cost', stat: '$1.8M', statLabel: 'cost of lifestyle inflation', source: 'Bureau of Labor Statistics',
    category: 'Budgeting',
  },
  {
    fact: "Missing just the 10 best trading days in any 20-year period cuts your return roughly in half. Staying invested beats timing the market.",
    concept: 'Market Timing Risk', stat: '~50%', statLabel: 'return lost by missing 10 best days', source: 'JPMorgan Asset Management',
    category: 'Investing',
  },
  {
    fact: "A 1% higher annual fee on a $500,000 portfolio costs $147,000 over 10 years — money that goes to the fund manager, not your retirement.",
    concept: 'Expense Ratio', stat: '$147K', statLabel: 'cost of 1% fee on $500K over 10 yrs', source: 'Vanguard',
    category: 'Investing',
  },
  {
    fact: "66% of Americans couldn't pass a basic financial literacy test. The countries with the highest financial literacy have the highest median net worth.",
    concept: 'Financial Literacy', stat: '66%', statLabel: 'of Americans fail basic financial quiz', source: 'FINRA',
    category: 'Education',
  },
  {
    fact: "The Rule of 72: divide 72 by your annual return to find how many years it takes to double your money. At 7%, money doubles every 10.3 years.",
    concept: 'Rule of 72', stat: '10.3 yrs', statLabel: 'to double money at 7% return', source: 'Financial Math',
    category: 'Investing',
  },
  {
    fact: "A household that contributes the max to a 401(k) for 30 years ($23,000/yr at 7%) accumulates $2.3 million — mostly from compounding, not contributions.",
    concept: '401(k) Power', stat: '$2.3M', statLabel: '30-year max 401(k) at 7% return', source: 'IRS / Planora',
    category: 'Retirement',
  },
  {
    fact: "The average retiree needs 70–90% of pre-retirement income to maintain their lifestyle. Most Americans retire with less than $200,000 saved.",
    concept: 'Retirement Gap', stat: '$200K', statLabel: 'median retirement savings in the US', source: 'Federal Reserve',
    category: 'Retirement',
  },
  {
    fact: "Paying an extra $200/month on a $400,000 mortgage at 7% eliminates 7 years of payments and saves over $118,000 in interest.",
    concept: 'Early Mortgage Payoff', stat: '$118K', statLabel: 'saved with $200/mo extra payment', source: 'Mortgage calculation',
    category: 'Real Estate',
  },
  {
    fact: "Tax-loss harvesting — selling losing positions to offset gains — can add 0.5–1.5% in after-tax returns annually. Most investors never use it.",
    concept: 'Tax-Loss Harvesting', stat: '+1.5%', statLabel: 'avg annual after-tax return boost', source: 'Vanguard',
    category: 'Tax Strategy',
  },
  {
    fact: "The average American pays $524,000 in interest over a lifetime — on mortgages, car loans, student debt, and credit cards. Debt is wealth in reverse.",
    concept: 'Lifetime Interest Cost', stat: '$524K', statLabel: 'avg lifetime interest paid per American', source: 'LendingTree',
    category: 'Debt',
  },
  {
    fact: "Roth IRA contributions grow tax-free forever. $6,000 contributed at age 22, never touched, becomes $91,000 by retirement at a 7% return.",
    concept: 'Roth IRA Compounding', stat: '15×', statLabel: 'growth on a single year\'s Roth contribution', source: 'IRS / Planora',
    category: 'Retirement',
  },
  {
    fact: "The 4% rule: a retiree can withdraw 4% of their portfolio in year one, adjust for inflation annually, and historically not run out of money over 30 years.",
    concept: '4% Withdrawal Rule', stat: '4%', statLabel: 'safe withdrawal rate over 30-year retirement', source: 'William Bengen, 1994',
    category: 'Retirement',
  },
  {
    fact: "Investors who trade frequently underperform buy-and-hold investors by 1.5–6.5% annually. Emotion is the most expensive investment strategy.",
    concept: 'Behavioral Finance', stat: '-6.5%', statLabel: 'annual underperformance from frequent trading', source: 'Dalbar QAIB',
    category: 'Investing',
  },
  {
    fact: "The USDA estimates the cost of raising a child to age 18 at $310,605 — before college. A 4-year private university averages $240,000 all-in.",
    concept: 'Cost of a Child', stat: '$310K', statLabel: 'average cost to raise a child to 18', source: 'USDA 2023',
    category: 'Family Planning',
  },
  {
    fact: "Asset location — placing bonds in tax-deferred accounts and stocks in taxable accounts — can add 0.2–0.8% annually with zero additional risk.",
    concept: 'Asset Location', stat: '+0.8%', statLabel: 'annual return from optimal asset location', source: 'Morningstar',
    category: 'Tax Strategy',
  },
  {
    fact: "Social Security delayed from 62 to 70 increases your monthly benefit by 76%. For a couple, the lifetime difference can exceed $250,000.",
    concept: 'Social Security Timing', stat: '+76%', statLabel: 'benefit increase from claiming at 70 vs 62', source: 'SSA',
    category: 'Retirement',
  },
  {
    fact: "The average car costs $12,182/year to own and operate. Over 40 years, investing that instead at 7% compounds to over $2.5 million.",
    concept: 'True Cost of a Car', stat: '$12K/yr', statLabel: 'average annual total cost of car ownership', source: 'AAA 2023',
    category: 'Budgeting',
  },
  {
    fact: "Inflation at 3% cuts the purchasing power of $100,000 in half in 24 years. Cash under the mattress is a guaranteed loss of wealth.",
    concept: 'Inflation Risk', stat: '24 yrs', statLabel: 'for 3% inflation to halve purchasing power', source: 'BLS',
    category: 'Macro',
  },
  {
    fact: "A Vanguard study found that a good financial advisor adds about 3% in net returns annually — mostly through behavioral coaching, not security selection.",
    concept: 'Advisor Alpha', stat: '+3%', statLabel: 'annual net return added by a good advisor', source: 'Vanguard Advisor\'s Alpha',
    category: 'Wealth Counsel',
  },
  {
    fact: "Index funds now hold over 50% of all US equity fund assets. The average actively managed fund underperforms its index benchmark over 15 years.",
    concept: 'Index vs. Active', stat: '92%', statLabel: 'of active large-cap funds underperform over 15 yrs', source: 'S&P SPIVA 2023',
    category: 'Investing',
  },
  {
    fact: "The break-even age for delaying Social Security from 62 to 70 is roughly 82. If you live past 82, waiting always wins financially.",
    concept: 'Break-Even Age', stat: '82', statLabel: 'break-even age for Social Security delay strategy', source: 'SSA',
    category: 'Retirement',
  },
  {
    fact: "Homeownership builds 40× more wealth than renting over a lifetime — largely through forced savings via equity and leverage on an appreciating asset.",
    concept: 'Homeownership Wealth', stat: '40×', statLabel: 'homeowner net worth vs. renter net worth', source: 'Federal Reserve',
    category: 'Real Estate',
  },
  {
    fact: "An emergency fund of 6 months of expenses prevents the need to liquidate investments during a crisis — protecting the compounding timeline that builds wealth.",
    concept: 'Emergency Fund', stat: '6 mos', statLabel: 'expenses recommended in liquid emergency fund', source: 'CFP Board',
    category: 'Budgeting',
  },
  {
    fact: "The top 10% of earners save 38% of their income. The bottom 20% save less than 1%. The gap in wealth comes from savings rate, not income alone.",
    concept: 'Savings Rate', stat: '38%', statLabel: 'savings rate of top 10% earners', source: 'Federal Reserve SCF',
    category: 'Budgeting',
  },
  {
    fact: "Term life insurance costs $30–$50/month for a healthy 30-year-old with a $1 million policy. Most people are underinsured relative to what their family actually needs.",
    concept: 'Life Insurance', stat: '$35/mo', statLabel: 'avg cost of $1M 20-yr term policy at age 30', source: 'Policygenius 2023',
    category: 'Insurance',
  },
  {
    fact: "Capital gains held longer than one year are taxed at 0–20%. Short-term gains are taxed as ordinary income — potentially at 37%. Patience is literally a tax strategy.",
    concept: 'Long-Term Capital Gains', stat: '0–20%', statLabel: 'long-term capital gains tax rate vs 37% short-term', source: 'IRS',
    category: 'Tax Strategy',
  },
  {
    fact: "Dollar-cost averaging — investing a fixed amount on a schedule — removes emotion from market timing and results in a lower average cost per share over time.",
    concept: 'Dollar-Cost Averaging', stat: 'DCA', statLabel: 'removes emotion from market entry timing', source: 'Financial Research',
    category: 'Investing',
  },
  {
    fact: "The median net worth of Americans aged 55–64 is $212,000. Most financial planners recommend having 10–12× your salary saved by retirement age.",
    concept: 'Retirement Readiness', stat: '$212K', statLabel: 'median net worth of Americans ages 55-64', source: 'Federal Reserve 2022',
    category: 'Retirement',
  },
  {
    fact: "529 plans grow tax-free and withdrawals for education are never taxed. Starting at birth vs. age 10 doubles the projected balance by college enrollment.",
    concept: '529 College Savings', stat: '2×', statLabel: 'more saved starting at birth vs. age 10', source: 'Vanguard / Planora',
    category: 'Education',
  },
  {
    fact: "Warren Buffett made 99% of his wealth after age 52. The most powerful variable in investing is not return — it is time in the market.",
    concept: 'Time in Market', stat: '99%', statLabel: 'of Buffett\'s wealth built after age 52', source: 'Morgan Housel',
    category: 'Investing',
  },
]

const CATEGORY_COLORS = {
  'Investing':       '#c9a96e',
  'Budgeting':       '#00B4C6',
  'Retirement':      '#818cf8',
  'Tax Strategy':    '#4a7c59',
  'Real Estate':     '#d4a017',
  'Debt':            '#c0392b',
  'Education':       '#818cf8',
  'Family Planning': '#00B4C6',
  'Macro':           '#a89070',
  'Wealth Counsel':  '#00B4C6',
  'Insurance':       '#4a7c59',
}

function DailyFactCard() {
  const today    = new Date()
  const dayOfYear = Math.floor((today - new Date(today.getFullYear(), 0, 0)) / 86400000)
  const fact     = DAILY_FACTS[dayOfYear % DAILY_FACTS.length]
  const color    = CATEGORY_COLORS[fact.category] || '#c9a96e'
  const monthNames = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
  const dateStr  = `${monthNames[today.getMonth()]} ${today.getDate()}, ${today.getFullYear()}`

  return (
    <div style={{ position: 'relative', width: 380 }}>
      {/* Stacked back cards */}
      <div style={{
        position: 'absolute', inset: 0,
        transform: 'translate(14px, 14px) rotate(2.2deg)',
        background: '#1c1510', border: '1px solid #3d3028',
        borderRadius: 18, opacity: 0.55,
      }} />
      <div style={{
        position: 'absolute', inset: 0,
        transform: 'translate(7px, 7px) rotate(1.1deg)',
        background: '#1f1812', border: '1px solid #3d3028',
        borderRadius: 18, opacity: 0.7,
      }} />

      {/* Main card */}
      <div style={{
        position: 'relative',
        background: 'rgba(35,28,22,0.98)',
        border: '1px solid #3d3028',
        borderRadius: 18,
        boxShadow: '0 28px 56px rgba(0,0,0,0.55), inset 0 1px 0 var(--border-c)',
        overflow: 'hidden',
      }}>
        {/* Top accent line */}
        <div style={{ height: 2, background: `linear-gradient(90deg, ${color} 0%, transparent 60%)` }} />

        <div style={{ padding: '20px 22px' }}>
          {/* Header */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 18 }}>
            <div>
              <div style={{ fontSize: 9, textTransform: 'uppercase', letterSpacing: '0.16em', color: '#6b5540', marginBottom: 4, fontFamily: UI }}>
                Daily Financial Fact
              </div>
              <div style={{ fontSize: 11, color: '#a89070', fontFamily: UI }}>
                {dateStr}
              </div>
            </div>
            <div style={{
              display: 'inline-flex', alignItems: 'center', gap: 5,
              background: `${color}14`, border: `1px solid ${color}30`,
              borderRadius: 6, padding: '4px 10px',
            }}>
              <span style={{ fontSize: 9, color, fontWeight: 700, fontFamily: UI, textTransform: 'uppercase', letterSpacing: '0.1em' }}>{fact.category}</span>
            </div>
          </div>

          {/* Fact text */}
          <p style={{
            fontFamily: DISPLAY, fontSize: 15, fontWeight: 400,
            color: '#f0e8d8', lineHeight: 1.65,
            margin: '0 0 20px', fontStyle: 'italic',
          }}>
            "{fact.fact}"
          </p>

          {/* Stat highlight */}
          <div style={{
            background: '#2d2419', border: '1px solid #3d3028',
            borderRadius: 10, padding: '12px 14px',
            display: 'flex', alignItems: 'center', gap: 12, marginBottom: 18,
          }}>
            <div style={{ fontFamily: MONO, fontSize: 22, fontWeight: 700, color, lineHeight: 1, flexShrink: 0 }}>
              {fact.stat}
            </div>
            <div>
              <div style={{ fontFamily: UI, fontSize: 11.5, color: '#a89070', lineHeight: 1.45 }}>{fact.statLabel}</div>
              <div style={{ fontFamily: UI, fontSize: 10, color: '#6b5540', marginTop: 3 }}>Source: {fact.source}</div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div style={{
          padding: '10px 22px 16px',
          borderTop: '1px solid #2a2018',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 7 }}>
            <div style={{ width: 5, height: 5, borderRadius: '50%', background: color, flexShrink: 0 }} />
            <span style={{ fontSize: 10, color: '#6b5540', fontFamily: UI }}>
              Concept: <span style={{ color: '#a89070', fontWeight: 600 }}>{fact.concept}</span>
            </span>
          </div>
          <span style={{ fontSize: 9, color: '#3d3028', fontFamily: UI, textTransform: 'uppercase', letterSpacing: '0.1em' }}>
            Updates daily
          </span>
        </div>
      </div>
    </div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// NAV
// ─────────────────────────────────────────────────────────────────────────────
function Nav() {
  const [scrolled,    setScrolled]    = useState(false)
  const [menuOpen,    setMenuOpen]    = useState(false)
  const [searchOpen,  setSearchOpen]  = useState(false)
  const [searchVal,   setSearchVal]   = useState('')
  const [showAccount, setShowAccount] = useState(false)
  const navigate = useNavigate()
  const { user, isAuthenticated, logout } = useAuth()

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 32)
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  const handleSearch = (e) => {
    e.preventDefault()
    if (searchVal.trim()) {
      navigate(`/ticker-lookup?q=${searchVal.trim().toUpperCase()}`)
      setSearchVal('')
      setSearchOpen(false)
    }
  }

  return (
    <>
      <motion.header style={{
        position: 'fixed', top: 0, left: 0, right: 0, zIndex: 500,
        transition: 'background 0.4s cubic-bezier(0.32,0.72,0,1), border-color 0.4s cubic-bezier(0.32,0.72,0,1)',
        background: scrolled ? 'rgba(26,20,16,0.94)' : 'transparent',
        backdropFilter: scrolled ? 'blur(20px)' : 'none',
        borderBottom: scrolled ? '1px solid #2a2018' : '1px solid transparent',
      }}>
        <div style={{
          maxWidth: 1400, margin: '0 auto', padding: '0 40px',
          height: 64, display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        }}>
          {/* Logo */}
          <button
            onClick={() => navigate('/')}
            style={{ background: 'none', border: 'none', cursor: 'pointer', textDecoration: 'none', display: 'flex', alignItems: 'baseline', gap: 2, padding: 0 }}
          >
            <span style={{ fontFamily: DISPLAY, fontSize: 20, fontWeight: 700, color: '#c9a96e', letterSpacing: '-0.01em', lineHeight: 1 }}>
              Planora
            </span>
          </button>

          {/* Center nav — desktop */}
          <nav style={{ display: 'flex', gap: 36, alignItems: 'center' }} className="planora-nav-center">
            {NAV_LINKS.map(link => (
              <button
                key={link.href}
                onClick={() => navigate(link.href)}
                style={{
                  background: 'none', border: 'none', cursor: 'pointer', padding: '0 0 2px',
                  fontSize: 13, fontWeight: 500, color: '#a89070',
                  letterSpacing: '0.01em', fontFamily: UI,
                  transition: 'color 0.2s cubic-bezier(0.32,0.72,0,1)',
                  borderBottom: '1px solid transparent',
                }}
                onMouseEnter={e => { e.currentTarget.style.color = '#f0e8d8' }}
                onMouseLeave={e => { e.currentTarget.style.color = '#a89070' }}
              >
                {link.label}
              </button>
            ))}
          </nav>

          {/* Right side */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
            {/* Search */}
            <button
              onClick={() => setSearchOpen(true)}
              style={{
                display: 'flex', alignItems: 'center', gap: 8,
                background: 'rgba(61,48,40,0.5)', border: '1px solid #3d3028',
                borderRadius: 8, padding: '6px 12px',
                color: '#a89070', fontSize: 12, fontFamily: UI, cursor: 'pointer',
                transition: 'all 0.2s cubic-bezier(0.32,0.72,0,1)',
              }}
              onMouseEnter={e => { e.currentTarget.style.borderColor = '#c9a96e50'; e.currentTarget.style.color = '#f0e8d8' }}
              onMouseLeave={e => { e.currentTarget.style.borderColor = '#3d3028';   e.currentTarget.style.color = '#a89070'  }}
              className="planora-nav-search"
            >
              <Search size={13} />
              <span>Search ticker</span>
              <span style={{ fontSize: 10, color: '#6b5540', background: '#2d2419', borderRadius: 4, padding: '1px 5px', fontFamily: MONO }}>
                ⌘K
              </span>
            </button>

            {/* Auth CTA */}
            {isAuthenticated ? (
              <div style={{ position: 'relative' }} className="planora-nav-cta">
                <button
                  onClick={() => setShowAccount(v => !v)}
                  style={{
                    display: 'inline-flex', alignItems: 'center', gap: 7,
                    background: '#2d2419', border: '1px solid #3d3028',
                    borderRadius: 8, padding: '6px 12px',
                    color: '#f0e8d8', fontSize: 12, fontWeight: 600, fontFamily: UI,
                    cursor: 'pointer', transition: 'border-color 0.2s',
                  }}
                  onMouseEnter={e => (e.currentTarget.style.borderColor = '#c9a96e50')}
                  onMouseLeave={e => (e.currentTarget.style.borderColor = '#3d3028')}
                >
                  <UserCircle size={14} color="#c9a96e" />
                  {user?.name?.split(' ')[0] || 'Account'}
                </button>
                <AnimatePresence>
                  {showAccount && (
                    <motion.div
                      initial={{ opacity: 0, y: 6, scale: 0.97 }}
                      animate={{ opacity: 1, y: 0, scale: 1 }}
                      exit={{ opacity: 0, y: 4, scale: 0.97 }}
                      transition={{ duration: 0.15 }}
                      style={{
                        position: 'absolute', top: 'calc(100% + 8px)', right: 0,
                        background: '#231c16', border: '1px solid #3d3028',
                        borderRadius: 10, padding: '8px 0', minWidth: 180,
                        boxShadow: '0 12px 32px rgba(0,0,0,0.5)',
                        zIndex: 200,
                      }}
                    >
                      <div style={{ padding: '8px 16px 10px', borderBottom: '1px solid #2a2018' }}>
                        <div style={{ fontFamily: UI, fontSize: 12, fontWeight: 700, color: '#f0e8d8' }}>{user?.name}</div>
                        <div style={{ fontFamily: UI, fontSize: 11, color: '#6b5540', marginTop: 2 }}>{user?.email}</div>
                      </div>
                      <button
                        onClick={() => { navigate('/dashboard') }}
                        style={{ display: 'flex', alignItems: 'center', gap: 8, width: '100%', padding: '9px 16px', background: 'none', border: 'none', cursor: 'pointer', fontFamily: UI, fontSize: 13, color: '#a89070', textAlign: 'left' }}
                        onMouseEnter={e => { e.currentTarget.style.background = '#2d2419'; e.currentTarget.style.color = '#f0e8d8' }}
                        onMouseLeave={e => { e.currentTarget.style.background = 'none'; e.currentTarget.style.color = '#a89070' }}
                      >
                        Enter Platform
                      </button>
                      <button
                        onClick={() => { logout(); setShowAccount(false) }}
                        style={{ display: 'flex', alignItems: 'center', gap: 8, width: '100%', padding: '9px 16px', background: 'none', border: 'none', cursor: 'pointer', fontFamily: UI, fontSize: 13, color: '#a89070', textAlign: 'left' }}
                        onMouseEnter={e => { e.currentTarget.style.background = '#2d2419'; e.currentTarget.style.color = '#c0392b' }}
                        onMouseLeave={e => { e.currentTarget.style.background = 'none'; e.currentTarget.style.color = '#a89070' }}
                      >
                        <LogOut size={13} /> Sign Out
                      </button>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            ) : (
              <div style={{ display: 'flex', gap: 8, alignItems: 'center' }} className="planora-nav-cta">
                <button
                  onClick={() => navigate('/login')}
                  style={{
                    display: 'inline-flex', alignItems: 'center', gap: 6,
                    background: 'transparent', border: '1px solid #3d3028',
                    borderRadius: 8, padding: '6px 14px',
                    color: '#a89070', fontSize: 12, fontWeight: 600, fontFamily: UI,
                    cursor: 'pointer', transition: 'all 0.2s',
                  }}
                  onMouseEnter={e => { e.currentTarget.style.borderColor = '#c9a96e50'; e.currentTarget.style.color = '#f0e8d8' }}
                  onMouseLeave={e => { e.currentTarget.style.borderColor = '#3d3028'; e.currentTarget.style.color = '#a89070' }}
                >
                  Sign In
                </button>
                <button
                  onClick={() => navigate('/dashboard')}
                  style={{
                    display: 'inline-flex', alignItems: 'center', gap: 6,
                    background: '#c9a96e', borderRadius: 8, padding: '7px 14px',
                    color: '#1a1410', fontSize: 12, fontWeight: 700, fontFamily: UI,
                    border: 'none', cursor: 'pointer', transition: 'opacity 0.2s',
                  }}
                  onMouseEnter={e => (e.currentTarget.style.opacity = '0.88')}
                  onMouseLeave={e => (e.currentTarget.style.opacity = '1')}
                >
                  Enter Platform
                </button>
              </div>
            )}

            {/* Hamburger */}
            <button
              onClick={() => setMenuOpen(true)}
              style={{
                background: 'none', border: 'none', color: '#a89070', cursor: 'pointer',
                padding: 4, display: 'flex', flexDirection: 'column', gap: 5,
              }}
              className="planora-nav-hamburger"
            >
              <span style={{ display: 'block', width: 20, height: 1.5, background: 'currentColor' }} />
              <span style={{ display: 'block', width: 14, height: 1.5, background: 'currentColor' }} />
            </button>
          </div>
        </div>
      </motion.header>

      {/* Search overlay */}
      <AnimatePresence>
        {searchOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            style={{
              position: 'fixed', inset: 0, zIndex: 600,
              background: 'rgba(10,8,5,0.92)', backdropFilter: 'blur(24px)',
              display: 'flex', alignItems: 'flex-start', justifyContent: 'center',
              paddingTop: 120,
            }}
            onClick={() => setSearchOpen(false)}
          >
            <motion.div
              initial={{ scale: 0.96, opacity: 0, y: -12 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.96, opacity: 0 }}
              transition={{ type: 'spring', stiffness: 400, damping: 30 }}
              onClick={e => e.stopPropagation()}
              style={{ width: '100%', maxWidth: 560, padding: '0 24px' }}
            >
              <form onSubmit={handleSearch}>
                <div style={{
                  background: '#231c16', border: '1px solid #3d3028', borderRadius: 14,
                  display: 'flex', alignItems: 'center', gap: 12, padding: '14px 18px',
                  boxShadow: '0 32px 64px rgba(0,0,0,0.6), inset 0 1px 0 var(--border-c)',
                }}>
                  <Search size={18} color="#6b5540" />
                  <input
                    autoFocus
                    value={searchVal}
                    onChange={e => setSearchVal(e.target.value.toUpperCase())}
                    placeholder="Search ticker — AAPL, MSFT, NVDA..."
                    style={{
                      flex: 1, background: 'none', border: 'none', outline: 'none',
                      fontSize: 16, color: '#f0e8d8', fontFamily: MONO, fontWeight: 500,
                    }}
                  />
                  <button
                    onClick={() => setSearchOpen(false)}
                    type="button"
                    style={{ background: 'none', border: 'none', color: '#6b5540', cursor: 'pointer', padding: 2 }}
                  >
                    <X size={16} />
                  </button>
                </div>
              </form>
              <p style={{ fontSize: 11, color: '#6b5540', marginTop: 10, paddingLeft: 4, letterSpacing: '0.04em', fontFamily: UI }}>
                Enter any US stock ticker to research — press Return to search
              </p>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Mobile menu */}
      <AnimatePresence>
        {menuOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            style={{
              position: 'fixed', inset: 0, zIndex: 600,
              background: 'rgba(15,12,9,0.97)', backdropFilter: 'blur(24px)',
              display: 'flex', flexDirection: 'column',
              padding: '24px 32px 48px',
            }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 48 }}>
              <span style={{ fontFamily: DISPLAY, fontSize: 20, fontWeight: 700, color: '#c9a96e' }}>Planora</span>
              <button onClick={() => setMenuOpen(false)} style={{ background: 'none', border: 'none', color: '#a89070', cursor: 'pointer', padding: 4 }}>
                <X size={20} />
              </button>
            </div>
            <nav style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 8 }}>
              {[...NAV_LINKS, { label: 'Enter Platform', href: '/dashboard' }].map((link, i) => (
                <motion.div
                  key={link.href}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.08 + i * 0.06, type: 'spring', stiffness: 300, damping: 28 }}
                >
                  <button
                    onClick={() => { setMenuOpen(false); navigate(link.href) }}
                    style={{
                      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                      width: '100%', padding: '18px 0',
                      borderBottom: '1px solid #2a2018',
                      background: 'none', border: 'none', borderBottom: '1px solid #2a2018',
                      color: link.label === 'Enter Platform' ? '#c9a96e' : '#f0e8d8',
                      cursor: 'pointer',
                    }}
                  >
                    <span style={{ fontFamily: DISPLAY, fontSize: 28, fontWeight: 600 }}>{link.label}</span>
                    <ArrowUpRight size={18} color={link.label === 'Enter Platform' ? '#c9a96e' : '#6b5540'} />
                  </button>
                </motion.div>
              ))}
            </nav>
            <p style={{ fontSize: 11, color: '#6b5540', letterSpacing: '0.08em', fontFamily: UI }}>
              Institutional Intelligence. Personal Impact.
            </p>
          </motion.div>
        )}
      </AnimatePresence>

      <style>{`
        @media (max-width: 900px) {
          .planora-nav-center { display: none !important; }
          .planora-nav-search { display: none !important; }
          .planora-nav-cta    { display: none !important; }
        }
        @media (min-width: 901px) {
          .planora-nav-hamburger { display: none !important; }
        }
      `}</style>
    </>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// HERO
// ─────────────────────────────────────────────────────────────────────────────
function Hero() {
  const ref   = useRef(null)
  const inView = useInView(ref, { once: true })

  return (
    <section
      ref={ref}
      style={{
        minHeight: '100dvh',
        background: '#1a1410',
        position: 'relative', overflow: 'hidden',
        display: 'flex', alignItems: 'center',
      }}
    >
      {/* Warm radial glow — left */}
      <div style={{
        position: 'absolute', top: '-10%', left: '-5%',
        width: '55%', height: '70%',
        background: 'radial-gradient(ellipse at top left, rgba(201,169,110,0.05) 0%, transparent 65%)',
        pointerEvents: 'none',
      }} />
      {/* Cool radial glow — right */}
      <div style={{
        position: 'absolute', bottom: '-10%', right: '5%',
        width: '40%', height: '60%',
        background: 'radial-gradient(ellipse at bottom right, rgba(0,180,198,0.04) 0%, transparent 65%)',
        pointerEvents: 'none',
      }} />

      <div
        style={{
          maxWidth: 1400, margin: '0 auto', padding: '80px 40px',
          width: '100%', display: 'grid',
          gridTemplateColumns: '1fr 1fr',
          gap: 80, alignItems: 'center',
        }}
        className="planora-hero-grid"
      >
        {/* Left content */}
        <div>
          {/* Eyebrow badge */}
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6, ease: EASE }}
            style={{
              display: 'inline-flex', alignItems: 'center', gap: 8,
              background: 'rgba(201,169,110,0.08)',
              border: '1px solid rgba(201,169,110,0.22)',
              borderRadius: 100, padding: '5px 12px', marginBottom: 28,
            }}
          >
            <motion.div
              animate={{ opacity: [1, 0.3, 1] }}
              transition={{ repeat: Infinity, duration: 2, ease: 'easeInOut' }}
              style={{ width: 5, height: 5, borderRadius: '50%', background: '#c9a96e' }}
            />
            <span style={{
              fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.2em',
              fontWeight: 600, color: '#c9a96e', fontFamily: UI,
            }}>
              Institutional Intelligence. Personal Impact.
            </span>
          </motion.div>

          {/* Headline — Playfair Display, staggered */}
          <h1 style={{
            fontFamily: DISPLAY, fontSize: 'clamp(40px,4.5vw,68px)',
            fontWeight: 700, color: '#f0e8d8',
            lineHeight: 1.06, letterSpacing: '-0.02em', margin: '0 0 24px',
          }}>
            {[
              { text: 'The foundation of',            delay: 0.10 },
              { text: 'every sound',                  delay: 0.18 },
              { text: <><span style={{ color: '#c9a96e', fontStyle: 'italic' }}>financial decision</span></>, delay: 0.26 },
              { text: 'starts here.',                 delay: 0.32 },
            ].map((line, i) => (
              <motion.span
                key={i}
                initial={{ opacity: 0, y: 20 }}
                animate={inView ? { opacity: 1, y: 0 } : {}}
                transition={{ duration: 0.7, delay: line.delay, ease: EASE }}
                style={{ display: 'block' }}
              >
                {line.text}
              </motion.span>
            ))}
          </h1>

          {/* Subheading */}
          <motion.p
            initial={{ opacity: 0, y: 16 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.7, delay: 0.38, ease: EASE }}
            style={{
              fontSize: 16, color: '#a89070', lineHeight: 1.75,
              maxWidth: 460, margin: '0 0 36px', fontFamily: UI,
            }}
          >
            Institutional-grade market intelligence, advisor collaboration, and financial
            education — unified for investors who want to understand before they act.
          </motion.p>

          {/* CTAs */}
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.7, delay: 0.46, ease: EASE }}
            style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 44 }}
          >
            <button
              onClick={() => window._planoraNavigate?.('/dashboard')}
              style={{
                display: 'inline-flex', alignItems: 'center', gap: 10,
                background: '#c9a96e', border: 'none', borderRadius: 10,
                padding: '13px 20px', color: '#1a1410',
                fontSize: 14, fontWeight: 700, fontFamily: UI,
                cursor: 'pointer',
                transition: 'all 0.25s cubic-bezier(0.32,0.72,0,1)',
              }}
              onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-2px)'; e.currentTarget.style.boxShadow = '0 8px 24px rgba(201,169,110,0.25)' }}
              onMouseLeave={e => { e.currentTarget.style.transform = 'translateY(0)';    e.currentTarget.style.boxShadow = 'none' }}
              onClick={() => { window.location.href = '/dashboard' }}
            >
              Enter Platform
              <span style={{
                width: 24, height: 24, borderRadius: '50%',
                background: 'rgba(26,20,16,0.15)',
                display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
              }}>
                <ArrowRight size={13} />
              </span>
            </button>

            <button
              onClick={() => { window.location.href = '/wealth-counsel' }}
              style={{
                display: 'inline-flex', alignItems: 'center', gap: 10,
                background: 'transparent', border: '1px solid rgba(201,169,110,0.3)',
                borderRadius: 10, padding: '13px 20px',
                color: '#c9a96e', fontSize: 14, fontWeight: 600, fontFamily: UI,
                cursor: 'pointer',
                transition: 'all 0.25s cubic-bezier(0.32,0.72,0,1)',
              }}
              onMouseEnter={e => { e.currentTarget.style.background = 'rgba(201,169,110,0.06)'; e.currentTarget.style.borderColor = 'rgba(201,169,110,0.5)' }}
              onMouseLeave={e => { e.currentTarget.style.background = 'transparent';             e.currentTarget.style.borderColor = 'rgba(201,169,110,0.3)' }}
            >
              Explore Solutions
            </button>
          </motion.div>

          {/* Trust row */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={inView ? { opacity: 1 } : {}}
            transition={{ duration: 0.8, delay: 0.58 }}
            style={{ display: 'flex', alignItems: 'center', gap: 16, flexWrap: 'wrap' }}
          >
            {['Real Data', 'Institutional Grade', 'Three Platforms'].map((t, i) => (
              <div key={t} style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
                <span style={{
                  fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.15em',
                  color: '#6b5540', fontFamily: UI, fontWeight: 500,
                }}>
                  {t}
                </span>
                {i < 2 && <span style={{ color: '#3d3028', fontSize: 10 }}>—</span>}
              </div>
            ))}
          </motion.div>
        </div>

        {/* Right — floating card */}
        <motion.div
          initial={{ opacity: 0, x: 40, y: 20 }}
          animate={inView ? { opacity: 1, x: 0, y: 0 } : {}}
          transition={{ duration: 0.9, delay: 0.3, ease: EASE }}
          style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}
        >
          <motion.div
            animate={{ y: [0, -10, 0] }}
            transition={{ repeat: Infinity, duration: 5.5, ease: 'easeInOut' }}
          >
            <DailyFactCard />
          </motion.div>
        </motion.div>
      </div>

      <style>{`
        @media (max-width: 900px) {
          .planora-hero-grid {
            grid-template-columns: 1fr !important;
            gap: 48px !important;
            padding: 100px 24px 60px !important;
          }
        }
      `}</style>
    </section>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// QUOTE SECTION
// ─────────────────────────────────────────────────────────────────────────────
function QuoteSection() {
  const ref    = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-80px' })

  return (
    <section
      ref={ref}
      style={{
        background: '#231c16',
        borderTop: '1px solid #2a2018',
        borderBottom: '1px solid #2a2018',
        padding: '80px 40px',
        position: 'relative', overflow: 'hidden',
      }}
    >
      <div style={{
        position: 'absolute', inset: 0,
        background: 'radial-gradient(ellipse 60% 80% at 50% 50%, rgba(201,169,110,0.03) 0%, transparent 70%)',
        pointerEvents: 'none',
      }} />

      <div style={{ maxWidth: 860, margin: '0 auto', textAlign: 'center', position: 'relative' }}>
        <motion.div
          initial={{ scaleX: 0 }}
          animate={inView ? { scaleX: 1 } : {}}
          transition={{ duration: 0.8, ease: EASE }}
          style={{
            height: 1,
            background: 'linear-gradient(to right, transparent, #c9a96e50, transparent)',
            marginBottom: 48, transformOrigin: 'center',
          }}
        />

        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, delay: 0.1, ease: EASE }}
          style={{
            fontFamily: DISPLAY, fontSize: 80, lineHeight: 0.6,
            color: '#c9a96e', opacity: 0.25,
            marginBottom: 24, display: 'block', userSelect: 'none',
          }}
        >
          &ldquo;
        </motion.div>

        <motion.blockquote
          initial={{ opacity: 0, y: 20 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8, delay: 0.18, ease: EASE }}
          style={{
            fontFamily: DISPLAY, fontSize: 'clamp(22px,3vw,36px)',
            fontStyle: 'italic', fontWeight: 500,
            color: '#f0e8d8', lineHeight: 1.55,
            margin: '0 0 32px', letterSpacing: '-0.01em',
          }}
        >
          Institutional intelligence that every investor deserves — not just the privileged few.
        </motion.blockquote>

        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.7, delay: 0.3, ease: EASE }}
          style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4 }}
        >
          <div style={{ width: 24, height: 1, background: '#c9a96e50', marginBottom: 10 }} />
          <span style={{ fontSize: 12, color: '#a89070', fontWeight: 600, letterSpacing: '0.08em', fontFamily: UI }}>
            The Planora Philosophy
          </span>
          <span style={{ fontSize: 11, color: '#6b5540', fontStyle: 'italic', fontFamily: UI }}>
            Bloomberg Terminal standards. Built for everyone.
          </span>
        </motion.div>

        <motion.div
          initial={{ scaleX: 0 }}
          animate={inView ? { scaleX: 1 } : {}}
          transition={{ duration: 0.8, delay: 0.2, ease: EASE }}
          style={{
            height: 1,
            background: 'linear-gradient(to right, transparent, #c9a96e50, transparent)',
            marginTop: 48, transformOrigin: 'center',
          }}
        />
      </div>
    </section>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// SECTION PREVIEW — asymmetric bento (Terminal big left, Wealth Counsel top right, FUN full width bottom)
// ─────────────────────────────────────────────────────────────────────────────
function TerminalCard({ inView }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 32 }}
      animate={inView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.7, delay: 0.1, ease: EASE }}
    >
      <div
        onClick={() => { window.location.href = '/terminal-hub' }}
        style={{
          background: '#231c16', border: '1px solid #3d3028', borderRadius: 20,
          overflow: 'hidden', cursor: 'pointer',
          transition: 'all 0.3s cubic-bezier(0.32,0.72,0,1)',
          boxShadow: 'inset 0 1px 0 var(--border-c)',
        }}
        onMouseEnter={e => {
          e.currentTarget.style.borderColor = 'rgba(201,169,110,0.4)'
          e.currentTarget.style.transform = 'translateY(-4px)'
          e.currentTarget.style.boxShadow = '0 20px 40px rgba(0,0,0,0.4), inset 0 1px 0 var(--border-c)'
        }}
        onMouseLeave={e => {
          e.currentTarget.style.borderColor = '#3d3028'
          e.currentTarget.style.transform = 'translateY(0)'
          e.currentTarget.style.boxShadow = 'inset 0 1px 0 var(--border-c)'
        }}
      >
        <div style={{ padding: '28px 28px 0' }}>
          {/* Tag */}
          <div style={{
            display: 'inline-flex', alignItems: 'center', gap: 6,
            background: 'rgba(201,169,110,0.1)', border: '1px solid rgba(201,169,110,0.2)',
            borderRadius: 6, padding: '4px 10px', marginBottom: 20,
          }}>
            <div style={{ width: 5, height: 5, borderRadius: '50%', background: '#c9a96e' }} />
            <span style={{ fontSize: 10, color: '#c9a96e', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.12em', fontFamily: UI }}>
              Planora Terminal
            </span>
          </div>

          <h3 style={{ fontFamily: DISPLAY, fontSize: 28, fontWeight: 700, color: '#f0e8d8', margin: '0 0 10px', letterSpacing: '-0.01em' }}>
            Markets &amp; Intelligence
          </h3>
          <p style={{ fontSize: 13, color: '#a89070', lineHeight: 1.65, margin: '0 0 20px', maxWidth: 360, fontFamily: UI }}>
            Real-time data, risk analysis, sector intelligence, and portfolio analytics.
            Research any ticker and understand it the way institutions do.
          </p>

          {/* Live market stats */}
          <div style={{ display: 'flex', gap: 20, marginBottom: 20 }}>
            {[
              { label: 'S&P 500', value: '5,847', chg: '+1.84%', up: true },
              { label: 'NDX',     value: '20,412', chg: '+2.31%', up: true },
              { label: 'VIX',     value: '13.4',  chg: '-0.8%',  up: false },
            ].map(s => (
              <div key={s.label}>
                <div style={{ fontSize: 10, color: '#6b5540', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: 3, fontFamily: UI }}>{s.label}</div>
                <div className="font-mono" style={{ fontSize: 14, fontWeight: 700, color: '#f0e8d8' }}>{s.value}</div>
                <div className="font-mono" style={{ fontSize: 11, color: s.up ? '#4a7c59' : '#8b3a3a' }}>{s.chg}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Chart bleeds to edge */}
        <ResponsiveContainer width="100%" height={80}>
          <AreaChart data={SP500_SPARK} margin={{ top: 0, right: 0, left: 0, bottom: 0 }}>
            <defs>
              <linearGradient id="terminalGrad" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%"   stopColor="#c9a96e" stopOpacity={0.35} />
                <stop offset="100%" stopColor="#c9a96e" stopOpacity={0}    />
              </linearGradient>
            </defs>
            <Area type="monotone" dataKey="v" stroke="#c9a96e" strokeWidth={1.5} fill="url(#terminalGrad)" dot={false} isAnimationActive={false} />
          </AreaChart>
        </ResponsiveContainer>

        <div style={{ padding: '14px 28px', borderTop: '1px solid #2a2018', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <span style={{ fontSize: 12, color: '#6b5540', fontFamily: UI }}>Risk analysis, sectors, portfolio, planning</span>
          <ArrowUpRight size={16} color="#c9a96e" />
        </div>
      </div>
    </motion.div>
  )
}

function WealthCounselCard({ inView }) {
  const features = ['Advisor Marketplace', 'Verified CFP Profiles', 'Specialization Matching', 'Fee Transparency']
  return (
    <motion.div
      initial={{ opacity: 0, y: 32 }}
      animate={inView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.7, delay: 0.2, ease: EASE }}
    >
      <div
        onClick={() => { window.location.href = '/wealth-counsel' }}
        style={{
          background: '#231c16', border: '1px solid #3d3028', borderRadius: 20,
          padding: 28, height: '100%', display: 'flex', flexDirection: 'column',
          cursor: 'pointer',
          transition: 'all 0.3s cubic-bezier(0.32,0.72,0,1)',
          boxShadow: 'inset 0 1px 0 var(--border-c)',
        }}
        onMouseEnter={e => {
          e.currentTarget.style.borderColor = 'rgba(0,180,198,0.35)'
          e.currentTarget.style.transform = 'translateY(-4px)'
          e.currentTarget.style.boxShadow = '0 20px 40px rgba(0,0,0,0.4), inset 0 1px 0 var(--border-c)'
        }}
        onMouseLeave={e => {
          e.currentTarget.style.borderColor = '#3d3028'
          e.currentTarget.style.transform = 'translateY(0)'
          e.currentTarget.style.boxShadow = 'inset 0 1px 0 var(--border-c)'
        }}
      >
        <div style={{
          display: 'inline-flex', alignItems: 'center', gap: 6,
          background: 'rgba(0,180,198,0.08)', border: '1px solid rgba(0,180,198,0.2)',
          borderRadius: 6, padding: '4px 10px', marginBottom: 20, alignSelf: 'flex-start',
        }}>
          <div style={{ width: 5, height: 5, borderRadius: '50%', background: '#00B4C6' }} />
          <span style={{ fontSize: 10, color: '#00B4C6', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.12em', fontFamily: UI }}>
            Wealth Counsel
          </span>
        </div>

        <h3 style={{ fontFamily: DISPLAY, fontSize: 24, fontWeight: 700, color: '#f0e8d8', margin: '0 0 10px', letterSpacing: '-0.01em' }}>
          Find Your Advisor
        </h3>
        <p style={{ fontSize: 13, color: '#a89070', lineHeight: 1.65, margin: '0 0 24px', fontFamily: UI }}>
          Browse verified CFP professionals matched to your goals — transparent fees, real credentials, no cold calls.
        </p>

        <div style={{ flex: 1 }} />

        <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 20 }}>
          {features.map(f => (
            <div key={f} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <div style={{ width: 3, height: 3, borderRadius: '50%', background: '#00B4C6', flexShrink: 0 }} />
              <span style={{ fontSize: 12, color: '#a89070', fontFamily: UI }}>{f}</span>
            </div>
          ))}
        </div>

        <div style={{ borderTop: '1px solid #2a2018', paddingTop: 14, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <span style={{ fontSize: 12, color: '#6b5540', fontFamily: UI }}>Advisor marketplace</span>
          <ArrowUpRight size={16} color="#00B4C6" />
        </div>
      </div>
    </motion.div>
  )
}

function FUNCard({ inView }) {
  const topics = [
    { label: 'Investing Basics',     color: '#c9a96e' },
    { label: 'Retirement Planning',  color: '#8b6340' },
    { label: 'Tax Strategy',         color: '#6b5540' },
    { label: 'Budgeting',            color: '#c9a96e' },
    { label: 'Estate Planning',      color: '#8b6340' },
    { label: 'Insurance',            color: '#6b5540' },
    { label: 'Debt & Credit',        color: '#c9a96e' },
    { label: 'Real Estate',          color: '#8b6340' },
  ]
  return (
    <motion.div
      initial={{ opacity: 0, y: 32 }}
      animate={inView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.7, delay: 0.3, ease: EASE }}
    >
      <div
        onClick={() => { window.location.href = '/education-hub' }}
        style={{
          background: '#231c16', border: '1px solid #3d3028', borderRadius: 20,
          padding: '28px 32px', cursor: 'pointer',
          transition: 'all 0.3s cubic-bezier(0.32,0.72,0,1)',
          boxShadow: 'inset 0 1px 0 var(--border-c)',
        }}
        onMouseEnter={e => {
          e.currentTarget.style.borderColor = 'rgba(129,140,248,0.35)'
          e.currentTarget.style.transform = 'translateY(-4px)'
          e.currentTarget.style.boxShadow = '0 20px 40px rgba(0,0,0,0.4), inset 0 1px 0 var(--border-c)'
        }}
        onMouseLeave={e => {
          e.currentTarget.style.borderColor = '#3d3028'
          e.currentTarget.style.transform = 'translateY(0)'
          e.currentTarget.style.boxShadow = 'inset 0 1px 0 var(--border-c)'
        }}
      >
        <div style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: 32, alignItems: 'center' }} className="fun-card-inner">
          <div>
            <div style={{
              display: 'inline-flex', alignItems: 'center', gap: 6,
              background: 'rgba(129,140,248,0.08)', border: '1px solid rgba(129,140,248,0.22)',
              borderRadius: 6, padding: '4px 10px', marginBottom: 16,
            }}>
              <div style={{ width: 5, height: 5, borderRadius: '50%', background: '#818cf8' }} />
              <span style={{ fontSize: 10, color: '#818cf8', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.12em', fontFamily: UI }}>
                Financial Education
              </span>
            </div>
            <h3 style={{ fontFamily: DISPLAY, fontSize: 24, fontWeight: 700, color: '#f0e8d8', margin: '0 0 8px', letterSpacing: '-0.01em' }}>
              FUN — Financial Understanding Network
            </h3>
            <p style={{ fontSize: 13, color: '#a89070', lineHeight: 1.65, margin: 0, fontFamily: UI, maxWidth: 420 }}>
              Tax strategy, retirement planning, investing fundamentals, estate protection — every dimension of financial life, explained like a patient professor.
            </p>
          </div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, maxWidth: 320 }}>
            {topics.map(t => (
              <span key={t.label} style={{
                fontSize: 11, fontFamily: UI, color: t.color,
                background: `${t.color}10`, border: `1px solid ${t.color}25`,
                borderRadius: 6, padding: '4px 10px', fontWeight: 500,
              }}>
                {t.label}
              </span>
            ))}
          </div>
        </div>
      </div>
    </motion.div>
  )
}

function SectionPreview() {
  const ref    = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-60px' })

  return (
    <section ref={ref} style={{ background: '#1a1410', padding: '100px 40px' }}>
      <div style={{ maxWidth: 1400, margin: '0 auto' }}>
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, ease: EASE }}
          style={{ marginBottom: 48 }}
        >
          <div style={{ fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.2em', color: '#6b5540', fontFamily: UI, fontWeight: 600, marginBottom: 12 }}>
            Everything you need
          </div>
          <h2 style={{
            fontFamily: DISPLAY, fontSize: 'clamp(28px,3.5vw,44px)',
            fontWeight: 700, color: '#f0e8d8',
            margin: 0, letterSpacing: '-0.02em', maxWidth: 480,
          }}>
            One platform. Three disciplines.
          </h2>
        </motion.div>

        {/* Asymmetric bento — NOT equal columns */}
        <div
          style={{ display: 'grid', gridTemplateColumns: '3fr 2fr', gridTemplateRows: 'auto auto', gap: 16 }}
          className="planora-preview-grid"
        >
          <TerminalCard inView={inView} />
          <WealthCounselCard inView={inView} />
          <div style={{ gridColumn: '1 / -1' }}>
            <FUNCard inView={inView} />
          </div>
        </div>
      </div>

      <style>{`
        @media (max-width: 768px) {
          .planora-preview-grid { grid-template-columns: 1fr !important; }
          .fun-card-inner        { grid-template-columns: 1fr !important; }
        }
        @media (max-width: 640px) {
          section { padding-left: 24px !important; padding-right: 24px !important; }
        }
      `}</style>
    </section>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// PLANNER SECTIONS — clickable section hub cards
// ─────────────────────────────────────────────────────────────────────────────
const PLANNER_SECTIONS = [
  {
    id: 'planning',
    icon: FileText,
    label: 'Financial Planning',
    tagline: 'The discipline that separates wealth builders from earners.',
    desc: 'Investment, retirement, tax, insurance, real estate, estate, and family planning — all in one place.',
    href: '/planning',
    stat: '2.5× more wealth',
    statLabel: 'for people with a written plan',
    accent: '#c9a96e',
    accentDim: 'rgba(201,169,110,0.08)',
    accentBdr: 'rgba(201,169,110,0.18)',
    subsections: ['Budget Planner', 'Retirement Planning', 'Tax Planning', 'Life Insurance', 'Estate Planning', 'Social Security'],
  },
  {
    id: 'markets',
    icon: BarChart2,
    label: 'Markets & Intelligence',
    tagline: 'Institutional-grade market data, live.',
    desc: 'Live indices, sector heat maps, top movers, market news, and terminal-grade data — Bloomberg quality.',
    href: '/markets',
    stat: '60s refresh',
    statLabel: 'on all live market data',
    accent: '#c9a96e',
    accentDim: 'rgba(201,169,110,0.08)',
    accentBdr: 'rgba(201,169,110,0.18)',
    subsections: ['Dashboard', 'Terminal', 'Market History', 'Sectors', 'Top Performers', 'Market News', 'Political Intelligence'],
  },
  {
    id: 'wealth',
    icon: TrendingUp,
    label: 'Wealth & Investing',
    tagline: 'Build and protect what you earn.',
    desc: 'Risk analysis, portfolio research, market breadth, insider flows, and investment tools — all connected.',
    href: '/wealth',
    stat: '7% avg',
    statLabel: 'annual S&P 500 real return',
    accent: '#c9a96e',
    accentDim: 'rgba(201,169,110,0.08)',
    accentBdr: 'rgba(201,169,110,0.18)',
    subsections: ['Risk Analysis', 'AI Reports', 'Brokerage Guide', 'Watchlist', 'Market Breadth', 'Insider Trading'],
  },
  {
    id: 'macro',
    icon: Globe,
    label: 'Macro & Economics',
    tagline: 'Understand the forces moving the world.',
    desc: 'Economic calendar, energy, labor, consumer trends, real estate data, and political intelligence — the macro context behind every market move.',
    href: '/macro',
    stat: '12+',
    statLabel: 'macro data streams tracked',
    accent: '#c9a96e',
    accentDim: 'rgba(201,169,110,0.08)',
    accentBdr: 'rgba(201,169,110,0.18)',
    subsections: ['Economic Calendar', 'Energy Markets', 'Labor Markets', 'The Consumer', 'Real Estate'],
  },
  {
    id: 'calculators',
    icon: BarChart2,
    label: 'Planning Calculators',
    tagline: 'Run the numbers before you decide.',
    desc: 'Compound growth, retirement projections, tax drag, insurance needs, mortgage analysis — every planning calculation in one place.',
    href: '/Calculators',
    stat: '20+',
    statLabel: 'interactive financial calculators',
    accent: '#c9a96e',
    accentDim: 'rgba(201,169,110,0.08)',
    accentBdr: 'rgba(201,169,110,0.18)',
    subsections: ['Compound Growth', 'Retirement Savings', 'Tax Drag Cost', 'Insurance Needs', 'Mortgage Analysis', 'Net Worth'],
  },
  {
    id: 'advisor',
    icon: Users,
    label: 'Wealth Counsel',
    tagline: 'Find the right advisor for your goals.',
    desc: 'Browse verified CFP professionals matched to your goals — transparent fees, real credentials, wealth counsel on your terms.',
    href: '/wealth-counsel',
    stat: 'Wealth Counsel',
    statLabel: 'advisor marketplace',
    accent: '#00B4C6',
    accentDim: 'rgba(0,180,198,0.08)',
    accentBdr: 'rgba(0,180,198,0.18)',
    subsections: ['Verified CFPs', 'Fee-Only Advisors', 'Goals Matching', 'Fiduciary Standard', 'Free to Browse', 'Wealth Planning'],
  },
  {
    id: 'fun',
    icon: BookOpen,
    label: 'FUN — Financial Understanding Network',
    tagline: 'Learn what they never taught you.',
    desc: 'Nine interactive modules covering every financial concept — budgeting, debt, investing, retirement, insurance, estate, and more. Each module combines education, calculators, and real frameworks you can act on today.',
    href: '/education-hub',
    stat: '66%',
    statLabel: 'of Americans are financially illiterate — FUN changes that',
    accent: '#818cf8',
    accentDim: 'rgba(129,140,248,0.08)',
    accentBdr: 'rgba(129,140,248,0.18)',
    subsections: ['Budgeting & Foundations', 'Debt & Credit', 'Investing Fundamentals', 'Retirement Concepts', 'Insurance Planning', 'Estate & Wills', 'Major Purchases', 'Life Events', 'Resource Directory'],
    wide: true,
  },
]

function PlannerSectionCard({ section, inView, delay }) {
  const navigate = useNavigate()
  const Icon = section.icon
  const [hovered, setHovered] = useState(false)

  const baseCard = {
    background: hovered ? '#271f18' : '#231c16',
    border: `1px solid ${hovered ? section.accentBdr : '#2a2018'}`,
    borderRadius: 16,
    padding: 0,
    textAlign: 'left',
    cursor: 'pointer',
    width: '100%',
    overflow: 'hidden',
    transform: hovered ? 'translateY(-3px)' : 'none',
    boxShadow: hovered ? `0 16px 48px rgba(0,0,0,0.4), 0 0 0 1px ${section.accentBdr}` : '0 2px 12px rgba(0,0,0,0.2)',
    transition: 'all 0.22s cubic-bezier(0.32,0.72,0,1)',
  }

  if (section.wide) {
    return (
      <motion.button
        variants={{ hidden: { opacity: 0, y: 24 }, show: { opacity: 1, y: 0, transition: { duration: 0.5, ease: EASE, delay } } }}
        onClick={() => navigate(section.href)}
        onMouseEnter={() => setHovered(true)}
        onMouseLeave={() => setHovered(false)}
        style={{ ...baseCard, display: 'flex', flexDirection: 'column', gridColumn: '1 / -1' }}
      >
        <div style={{ height: 2, background: hovered ? `linear-gradient(90deg, ${section.accent}, transparent 50%)` : 'transparent', transition: 'background 0.22s ease' }} />
        <div style={{ padding: '1.75rem 2rem', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2.5rem', alignItems: 'center' }} className="fun-wide-inner">
          {/* Left */}
          <div>
            <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '1rem' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                <div style={{ width: 38, height: 38, borderRadius: 10, background: section.accentDim, border: `1px solid ${section.accentBdr}`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                  <Icon size={16} color={section.accent} />
                </div>
                <div style={{ fontFamily: "'Inter', system-ui, sans-serif", fontSize: '0.9375rem', fontWeight: 700, color: '#f0e8d8' }}>{section.label}</div>
              </div>
              <ArrowUpRight size={14} color={hovered ? section.accent : '#6b5540'} style={{ transition: 'color 0.2s', flexShrink: 0 }} />
            </div>
            <div style={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: '0.8125rem', fontStyle: 'italic', color: section.accent, marginBottom: 10, lineHeight: 1.4 }}>{section.tagline}</div>
            <div style={{ fontFamily: "'Inter', system-ui, sans-serif", fontSize: '0.8125rem', color: '#a89070', lineHeight: 1.65, marginBottom: '1.25rem' }}>{section.desc}</div>
            <div style={{ display: 'flex', alignItems: 'baseline', gap: 6, paddingTop: '1rem', borderTop: '1px solid #2a2018' }}>
              <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: '1.0625rem', fontWeight: 700, color: section.accent }}>{section.stat}</span>
              <span style={{ fontFamily: "'Inter', system-ui, sans-serif", fontSize: '0.6875rem', color: '#6b5540', lineHeight: 1.4 }}>{section.statLabel}</span>
            </div>
          </div>
          {/* Right — pills grid */}
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 7 }}>
            {section.subsections.map(s => (
              <span key={s} style={{
                fontFamily: "'Inter', system-ui, sans-serif", fontSize: '0.6875rem', fontWeight: 600,
                color: section.accent, background: section.accentDim,
                border: `1px solid ${section.accentBdr}`,
                borderRadius: 6, padding: '5px 10px', whiteSpace: 'nowrap',
              }}>{s}</span>
            ))}
          </div>
        </div>
      </motion.button>
    )
  }

  return (
    <motion.button
      variants={{ hidden: { opacity: 0, y: 24 }, show: { opacity: 1, y: 0, transition: { duration: 0.5, ease: EASE, delay } } }}
      onClick={() => navigate(section.href)}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{ ...baseCard, display: 'flex', flexDirection: 'column' }}
    >
      {/* Top accent bar */}
      <div style={{ height: 2, background: hovered ? `linear-gradient(90deg, ${section.accent}, transparent)` : 'transparent', transition: 'background 0.22s ease' }} />

      <div style={{ padding: '1.5rem' }}>
        {/* Icon + arrow */}
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '1.125rem' }}>
          <div style={{ width: 38, height: 38, borderRadius: 10, background: section.accentDim, border: `1px solid ${section.accentBdr}`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
            <Icon size={16} color={section.accent} />
          </div>
          <ArrowUpRight size={14} color={hovered ? section.accent : '#6b5540'} style={{ transition: 'color 0.2s' }} />
        </div>

        {/* Label + tagline */}
        <div style={{ fontFamily: "'Inter', system-ui, sans-serif", fontSize: '0.9375rem', fontWeight: 700, color: '#f0e8d8', marginBottom: 6 }}>{section.label}</div>
        <div style={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: '0.8125rem', fontStyle: 'italic', color: section.accent, marginBottom: 10, lineHeight: 1.4 }}>{section.tagline}</div>
        <div style={{ fontFamily: "'Inter', system-ui, sans-serif", fontSize: '0.8125rem', color: '#a89070', lineHeight: 1.65, marginBottom: '1.25rem' }}>{section.desc}</div>

        {/* Sub-section pills */}
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: '1.25rem' }}>
          {section.subsections.map(s => (
            <span key={s} style={{ fontFamily: "'Inter', system-ui, sans-serif", fontSize: '0.625rem', fontWeight: 600, color: '#6b5540', background: '#2d2419', border: '1px solid #2a2018', borderRadius: 5, padding: '2px 7px', whiteSpace: 'nowrap' }}>{s}</span>
          ))}
        </div>

        {/* Stat footer */}
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 6, paddingTop: '0.875rem', borderTop: '1px solid #2a2018' }}>
          <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: '1.0625rem', fontWeight: 700, color: section.accent }}>{section.stat}</span>
          <span style={{ fontFamily: "'Inter', system-ui, sans-serif", fontSize: '0.6875rem', color: '#6b5540', lineHeight: 1.4 }}>{section.statLabel}</span>
        </div>
      </div>
    </motion.button>
  )
}

function PlannerSections() {
  const ref    = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-60px' })

  return (
    <section ref={ref} style={{ background: '#1a1410', borderTop: '1px solid #2a2018', padding: '100px 40px' }}>
      <div style={{ maxWidth: 1400, margin: '0 auto' }}>
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, ease: EASE }}
          style={{ marginBottom: 56 }}
        >
          <div style={{ fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.2em', color: '#6b5540', fontFamily: "'Inter', system-ui, sans-serif", fontWeight: 600, marginBottom: 12 }}>
            Explore the platform
          </div>
          <div style={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', flexWrap: 'wrap', gap: 16 }}>
            <h2 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 'clamp(26px,3.2vw,42px)', fontWeight: 700, color: '#f0e8d8', margin: 0, letterSpacing: '-0.02em' }}>
              Seven disciplines.<em style={{ fontStyle: 'italic', color: '#c9a96e' }}> One ecosystem.</em>
            </h2>
            <p style={{ fontFamily: "'Inter', system-ui, sans-serif", fontSize: '0.875rem', color: '#6b5540', maxWidth: 380, lineHeight: 1.7, margin: 0 }}>
              Each section explains what it covers, why it matters, and gives you the tools to act on it. Click any card to go deeper.
            </p>
          </div>
        </motion.div>

        <motion.div
          variants={{ hidden: {}, show: { transition: { staggerChildren: 0.06 } } }}
          initial="hidden"
          animate={inView ? 'show' : 'hidden'}
          style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1.125rem' }}
          className="planner-sections-grid"
        >
          {PLANNER_SECTIONS.map((s, i) => (
            <PlannerSectionCard key={s.id} section={s} inView={inView} delay={i * 0.06} />
          ))}
        </motion.div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={inView ? { opacity: 1 } : {}}
          transition={{ duration: 0.6, delay: 0.5 }}
          style={{ marginTop: 40, display: 'flex', alignItems: 'center', gap: 12, justifyContent: 'center' }}
        >
          <div style={{ width: 1, height: 20, background: '#2a2018' }} />
          <span style={{ fontFamily: "'Inter', system-ui, sans-serif", fontSize: '0.75rem', color: '#6b5540' }}>
            Press <strong style={{ color: '#a89070', fontFamily: "'Playfair Display', Georgia, serif", fontStyle: 'italic' }}>P</strong> inside the platform to navigate between all sections
          </span>
          <div style={{ width: 1, height: 20, background: '#2a2018' }} />
        </motion.div>
      </div>

      <style>{`
        @media (max-width: 900px) { .planner-sections-grid { grid-template-columns: repeat(2, 1fr) !important; } }
        @media (max-width: 580px) { .planner-sections-grid { grid-template-columns: 1fr !important; } }
        @media (max-width: 640px) { .fun-wide-inner { grid-template-columns: 1fr !important; } }
      `}</style>
    </section>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// FEATURED INSIGHT — rotating educational content with concept sidebar
// ─────────────────────────────────────────────────────────────────────────────
function FeaturedInsight() {
  const [active, setActive] = useState(0)
  const ref    = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-60px' })
  const insight = INSIGHTS[active]

  return (
    <section ref={ref} style={{ background: '#231c16', borderTop: '1px solid #2a2018', padding: '100px 40px' }}>
      <div style={{ maxWidth: 1400, margin: '0 auto' }}>
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, ease: EASE }}
          style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 48, flexWrap: 'wrap', gap: 16 }}
        >
          <div>
            <div style={{ fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.2em', color: '#6b5540', fontFamily: UI, fontWeight: 600, marginBottom: 10 }}>
              Featured Insight
            </div>
            <h2 style={{ fontFamily: DISPLAY, fontSize: 'clamp(24px,3vw,38px)', fontWeight: 700, color: '#f0e8d8', margin: 0, letterSpacing: '-0.02em' }}>
              Learn from the principles,<br />not the headlines.
            </h2>
          </div>

          {/* Tab selectors */}
          <div style={{ display: 'flex', gap: 8 }}>
            {INSIGHTS.map((_, i) => (
              <button
                key={i}
                onClick={() => setActive(i)}
                style={{
                  background: i === active ? '#c9a96e' : 'transparent',
                  border: `1px solid ${i === active ? '#c9a96e' : '#3d3028'}`,
                  borderRadius: 8, padding: '6px 14px',
                  fontSize: 11, fontFamily: UI, fontWeight: 600,
                  color: i === active ? '#1a1410' : '#6b5540',
                  cursor: 'pointer',
                  transition: 'all 0.2s cubic-bezier(0.32,0.72,0,1)',
                }}
              >
                0{i + 1}
              </button>
            ))}
          </div>
        </motion.div>

        {/* Content */}
        <AnimatePresence mode="wait">
          <motion.div
            key={active}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            transition={{ duration: 0.45, ease: EASE }}
            style={{ display: 'grid', gridTemplateColumns: '1fr 380px', gap: 48, alignItems: 'start' }}
            className="planora-insight-grid"
          >
            {/* Left */}
            <div>
              <div style={{
                display: 'inline-flex', alignItems: 'center', gap: 6,
                background: 'rgba(201,169,110,0.08)', border: '1px solid rgba(201,169,110,0.2)',
                borderRadius: 6, padding: '4px 10px', marginBottom: 20,
              }}>
                <span style={{ fontSize: 10, color: '#c9a96e', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.12em', fontFamily: UI }}>
                  {insight.category}
                </span>
              </div>

              <h3 style={{
                fontFamily: DISPLAY, fontSize: 'clamp(22px,2.5vw,32px)',
                fontWeight: 700, color: '#f0e8d8',
                lineHeight: 1.25, margin: '0 0 20px', letterSpacing: '-0.02em',
              }}>
                {insight.headline}
              </h3>

              <p style={{
                fontSize: 15, color: '#a89070', lineHeight: 1.8,
                margin: '0 0 28px', fontFamily: UI, maxWidth: 560,
              }}>
                {insight.excerpt}
              </p>

              {/* Quote */}
              <div style={{ borderLeft: '2px solid #c9a96e50', paddingLeft: 20, marginBottom: 32 }}>
                <p style={{ fontFamily: DISPLAY, fontSize: 16, fontStyle: 'italic', color: '#a89070', margin: '0 0 8px', lineHeight: 1.55 }}>
                  &ldquo;{insight.quote}&rdquo;
                </p>
                <span style={{ fontSize: 11, color: '#6b5540', fontFamily: UI }}>— {insight.quoteAttr}</span>
              </div>

              <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
                <button
                  onClick={() => { window.location.href = '/insights' }}
                  style={{
                    display: 'inline-flex', alignItems: 'center', gap: 8,
                    background: 'transparent', border: '1px solid rgba(201,169,110,0.3)',
                    borderRadius: 9, padding: '10px 18px',
                    color: '#c9a96e', fontSize: 13, fontWeight: 600, fontFamily: UI,
                    cursor: 'pointer',
                    transition: 'all 0.25s cubic-bezier(0.32,0.72,0,1)',
                  }}
                  onMouseEnter={e => { e.currentTarget.style.background = 'rgba(201,169,110,0.08)'; e.currentTarget.style.borderColor = 'rgba(201,169,110,0.5)' }}
                  onMouseLeave={e => { e.currentTarget.style.background = 'transparent';             e.currentTarget.style.borderColor = 'rgba(201,169,110,0.3)' }}
                >
                  Explore this topic <ArrowRight size={13} />
                </button>
                <span style={{ fontSize: 11, color: '#6b5540', fontFamily: UI }}>{insight.readTime}</span>
              </div>
            </div>

            {/* Right — concept card */}
            <div style={{
              background: '#2d2419', border: '1px solid #3d3028',
              borderRadius: 16, padding: 28,
              boxShadow: 'inset 0 1px 0 var(--elevated)',
            }}>
              <div style={{ fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.16em', color: '#6b5540', fontFamily: UI, marginBottom: 12 }}>
                Core Concept
              </div>
              <div style={{ fontFamily: DISPLAY, fontSize: 20, fontWeight: 700, color: '#c9a96e', margin: '0 0 12px', letterSpacing: '-0.01em' }}>
                {insight.concept}
              </div>
              <p style={{ fontSize: 13, color: '#a89070', lineHeight: 1.7, margin: '0 0 24px', fontFamily: UI }}>
                {insight.definition}
              </p>

              <div style={{ height: 1, background: '#3d3028', marginBottom: 20 }} />

              <div style={{ fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.16em', color: '#6b5540', fontFamily: UI, marginBottom: 12 }}>
                Further Reading
              </div>
              {insight.books.map(book => (
                <div key={book} style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
                  <div style={{ width: 3, height: 3, borderRadius: '50%', background: '#6b5540', flexShrink: 0 }} />
                  <span style={{ fontSize: 12, color: '#6b5540', fontFamily: UI, fontStyle: 'italic' }}>{book}</span>
                </div>
              ))}
            </div>
          </motion.div>
        </AnimatePresence>
      </div>

      <style>{`
        @media (max-width: 900px) {
          .planora-insight-grid { grid-template-columns: 1fr !important; }
        }
        @media (max-width: 640px) {
          section { padding-left: 24px !important; padding-right: 24px !important; }
        }
      `}</style>
    </section>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// FOOTER
// ─────────────────────────────────────────────────────────────────────────────
const FOOTER_COLS = [
  {
    heading: 'Terminal',
    links: [
      { label: 'Market Overview',   href: '/dashboard'        },
      { label: 'Risk Analysis',     href: '/risk-analysis'    },
      { label: 'Sector Analysis',   href: '/sectors'          },
      { label: 'Portfolio Tools',   href: '/dashboard'        },
    ],
  },
  {
    heading: 'Markets',
    links: [
      { label: 'Market History',    href: '/MarketHistory'    },
      { label: 'Market News',       href: '/market-news'      },
      { label: 'Economic Calendar', href: '/economic-calendar'},
      { label: 'Top Performers',    href: '/top-performers'   },
    ],
  },
  {
    heading: 'Macro',
    links: [
      { label: 'Energy Markets',    href: '/energy'           },
      { label: 'Labor Markets',     href: '/labor'            },
      { label: 'Consumer Market',   href: '/consumer'         },
      { label: 'Real Estate',       href: '/real-estate'      },
    ],
  },
  {
    heading: 'Plan',
    links: [
      { label: 'Tax Planning',      href: '/tax-planning'      },
      { label: 'Retirement',        href: '/retirement-planning'},
      { label: 'Wealth Counsel',    href: '/wealth-counsel'    },
      { label: 'Estate Planning',   href: '/FuturePlanning'    },
    ],
  },
  {
    heading: 'Education',
    links: [
      { label: 'FUN Platform',      href: '/fun'              },
      { label: 'Calculators',       href: '/calculators'      },
      { label: 'AI Advisor',        href: '/ai-advisor'       },
    ],
  },
]

function Footer() {
  const navigate = useNavigate()
  return (
    <footer style={{ background: '#0f0c09', borderTop: '1px solid #2a2018' }}>
      <div style={{ maxWidth: 1400, margin: '0 auto', padding: '64px 40px 48px' }}>
        {/* Top row */}
        <div style={{ display: 'grid', gridTemplateColumns: '240px 1fr', gap: 80, marginBottom: 56 }} className="planora-footer-main">
          {/* Brand */}
          <div>
            <button onClick={() => navigate('/')} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, display: 'block', marginBottom: 10 }}>
              <span style={{ fontFamily: DISPLAY, fontSize: 22, fontWeight: 700, color: '#c9a96e' }}>Planora</span>
            </button>
            <p style={{ fontSize: 13, color: '#6b5540', lineHeight: 1.7, maxWidth: 200, margin: '0 0 20px', fontFamily: UI }}>
              Institutional Intelligence. Personal Impact.
            </p>
            <p style={{ fontSize: 11, color: '#3d3028', lineHeight: 1.6, fontFamily: UI }}>
              For educational purposes only.<br />Not financial advice.
            </p>
          </div>

          {/* Nav columns */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 24 }} className="planora-footer-nav">
            {FOOTER_COLS.map(col => (
              <div key={col.heading}>
                <div style={{ fontSize: 10, fontWeight: 600, color: '#6b5540', textTransform: 'uppercase', letterSpacing: '0.14em', marginBottom: 16, fontFamily: UI }}>
                  {col.heading}
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                  {col.links.map(l => (
                    <button
                      key={l.href}
                      onClick={() => navigate(l.href)}
                      style={{
                        background: 'none', border: 'none', cursor: 'pointer',
                        fontSize: 12, color: '#6b5540', fontFamily: UI,
                        textAlign: 'left', padding: 0, lineHeight: 1.4,
                        transition: 'color 0.2s',
                      }}
                      onMouseEnter={e => (e.currentTarget.style.color = '#a89070')}
                      onMouseLeave={e => (e.currentTarget.style.color = '#6b5540')}
                    >
                      {l.label}
                    </button>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Divider */}
        <div style={{ height: 1, background: '#2a2018', marginBottom: 28 }} />

        {/* Bottom */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 24, flexWrap: 'wrap' }}>
          <p style={{ fontSize: 11, color: '#3d3028', maxWidth: 600, lineHeight: 1.7, margin: 0, fontFamily: UI }}>
            Planora is an educational and research platform only. Nothing on this site constitutes
            financial, investment, tax, legal, or accounting advice. All data is provided for
            informational purposes. Consult a qualified professional for your specific situation.
            Past performance does not guarantee future results.
          </p>
          <p style={{ fontSize: 11, color: '#3d3028', whiteSpace: 'nowrap', margin: 0, fontFamily: UI }}>
            &copy; {new Date().getFullYear()} Planora
          </p>
        </div>
      </div>

      <style>{`
        @media (max-width: 1024px) {
          .planora-footer-main { grid-template-columns: 1fr !important; gap: 40px !important; }
          .planora-footer-nav  { grid-template-columns: repeat(3,1fr) !important; }
        }
        @media (max-width: 640px) {
          .planora-footer-nav  { grid-template-columns: repeat(2,1fr) !important; }
        }
      `}</style>
    </footer>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// LANDING PAGE — root export
// ─────────────────────────────────────────────────────────────────────────────
export default function Landing() {
  return (
    <div style={{ background: '#1a1410', minHeight: '100dvh', fontFamily: UI }}>
      <Nav />
      <Hero />
      <QuoteSection />
      <SectionPreview />
      <PlannerSections />
      <FeaturedInsight />
      <Footer />
    </div>
  )
}
